### ISSUE TITLE
QR code scanner does not work on Android in current develop builds

### ISSUE THREAD

**Issue by RagingCactus** [graphefruit/Beanconqueror#846]
The app crashes when trying to scan a QR code in current `develop` builds on Android:

```
FATAL EXCEPTION: main
Process: com.beanconqueror.app, PID: 16703
java.lang.NoSuchFieldError: No field Companion of type Landroidx/camera/lifecycle/ProcessCameraProvider$Companion; in class Landroidx/camera/lifecycle/ProcessCameraProvider; or its superclasses (declaration of 'androidx.camera.lifecycle.ProcessCameraProvider' appears in /data/app/~~tRaYV5en6-HDEJfMHA_V2g==/com.beanconqueror.app-1VmERoxpnKTYLOXdah2uuw==/base.apk)
	at com.outsystems.plugins.barcode.view.OSBARCScannerActivity.ScanScreen(OSBARCScannerActivity.kt:274)
	at com.outsystems.plugins.barcode.view.OSBARCScannerActivity$onCreate$3$1.invoke(OSBARCScannerActivity.kt:204)
	at com.outsystems.plugins.barcode.view.OSBARCScannerActivity$onCreate$3$1.invoke(OSBARCScannerActivity.kt:203)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
	at androidx.compose.material3.TextKt.ProvideTextStyle(Text.kt:360)
	at androidx.compose.material3.MaterialThemeKt$MaterialTheme$1.invoke(MaterialTheme.kt:81)
	at androidx.compose.material3.MaterialThemeKt$MaterialTheme$1.invoke(MaterialTheme.kt:80)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
	at androidx.compose.material3.MaterialThemeKt.MaterialTheme(MaterialTheme.kt:73)
	at com.outsystems.plugins.barcode.view.ui.theme.ThemeKt.BarcodeScannerTheme(Theme.kt:65)
	at com.outsystems.plugins.barcode.view.OSBARCScannerActivity$onCreate$3.invoke(OSBARCScannerActivity.kt:203)
	at com.outsystems.plugins.barcode.view.OSBARCScannerActivity$onCreate$3.invoke(OSBARCScannerActivity.kt:197)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.compose.ui.platform.ComposeView.Content(ComposeView.android.kt:428)
	at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:252)
	at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:251)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
	at androidx.compose.ui.platform.CompositionLocalsKt.ProvideCommonCompositionLocals(CompositionLocals.kt:194)
	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:123)
	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:122)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt.ProvideAndroidCompositionLocals(AndroidCompositionLocals.android.kt:114)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$2.invoke(Wrapper.android.kt:156)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$2.invoke(Wrapper.android.kt:155)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
```

Root cause: https://github.com/ionic-team/capacitor-barcode-scanner/pull/40 and https://github.com/ionic-team/capacitor-barcode-scanner/issues/41 

This also breaks on older commits now because `capacitor-barcode-scanner` uses dynamic version specifier:
```
    implementation "com.github.outsystems:osbarcode-android:[1.0.1, 2.0.0[@aar"

```

**Comment by graphefruit** [comment]
Thank you!

**Comment by RagingCactus** [comment]
This only affects `develop` and is fixed in `develop`, so I'll close this.
/close
